name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - python-dotenv
    - pandas
    - numpy==1.23.5
    - scikit-learn==1.3.2
    - mlflow==2.8.0
    - mlflow-skinny == 2.7.0
    - azureml-mlflow == 1.61.0
    - azure-ai-ml>=1.30.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
