name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - python-dotenv
    - pandas
    - numpy==1.23.5
    - scikit-learn==1.3.2
    # Fixed MLflow compatibility - pin exact versions to avoid azureml_artifacts_builder error
    - mlflow==2.9.2
    - azureml-mlflow==1.55.0
    - azure-ai-ml>=1.10.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
