name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow==2.14.3
    - azureml-mlflow==1.83.0
    - azure-ai-ml>=1.30.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
    - azureml-inference-server-http
    - Werkzeug==2.3.8
    - tqdm
    - nltk
    - numpy
    - pyyaml
    - flake8
    - black