name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - python-dotenv
    - pandas
    - numpy==1.26.4
    - scikit-learn==1.3.2
    - mlflow-skinny==2.14.3
    - azureml-mlflow==1.60.0
    - azure-ai-ml>=1.30.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
    # Removed pinned AzureML v1 packages (azureml-core, defaults, dataset-runtime, contrib, automl, inference-server)
    # to avoid dependency resolution conflicts with azureml-mlflow 1.61.x and azure-ai-ml v2 SDK.
    # azureml-mlflow will pull a compatible azureml-core version automatically if required.
    - inference-schema
    - MarkupSafe>=2.1.2
    - pybind11
    - urllib3>=1.26.18
    - cryptography>=41.0.4
    - aiohttp>=3.8.5
    - requests
    - tqdm
    - nltk
    - numpy==1.26.4
    - pyyaml
    - flake8
    - black
