name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - tqdm
    - nltk
    - numpy
    - pyyaml
    - flake8
    - pandas
    - black
    - azureml-core==1.60.0
    - azureml-dataset-runtime[fuse]==1.60.0
