name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy==1.26.4
    - scikit-learn==1.3.2
    - mlflow-skinny==2.14.3
    - azureml-mlflow==1.60.0
    - azure-ai-ml>=1.30.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
    - azureml-inference-server-http
    - Werkzeug==2.3.8